# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 02:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('atender', models.BooleanField(default=False)),
                ('has_pagado', models.BooleanField(default=False)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('sumamary', models.TextField(max_length=255)),
                ('contenido', models.TextField()),
                ('lugar', models.CharField(max_length=50)),
                ('inicio', models.DateTimeField()),
                ('finalizado', models.DateTimeField()),
                ('imagen', models.ImageField(upload_to='events')),
                ('is_free', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Category')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comentarios',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Evento'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistentes',
            name='evento',
            field=models.ManyToManyField(to='notas.Evento'),
        ),
    ]
